# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b9ecc61bc453badc5b86ebeeb088c1e0"
name = "shipwise-rate-pull"
application_url = "https://live-rate-shop.onrender.com"
redirect_urls = [ "https://live-rate-shop.onrender.com/auth/callback" ]
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

# ?? ADD THIS LINE UNDER [build] (replace with your dev store domain)
# dev_store_url = "33d-dev.myshopify.com"

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

 [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_shipping,write_shipping"

[auth]
redirect_urls = [ "https://live-rate-shop.onrender.com/auth/callback" ]
