# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b9ecc61bc453badc5b86ebeeb088c1e0"
name = "33 Degrees Rates"
application_url = "https://shopifyapp-e92y.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[access_scopes]
scopes = "read_shipping,write_shipping,read_products"

[auth]
redirect_urls = [ "https://shopifyapp-e92y.onrender.com/auth/callback" ]
